### ISSUE TITLE
What should I do to use it

### ISSUE THREAD

**Issue by denstiny** [doums/baru#1]

**Comment by doums** [comment]
Hi,

First if you use Arch Linux I planned to make an AUR package soon.\
But for now, the only way is to clone the repo, install the required toolchain, and build it.

To install the toolchain follow the officials steps https://www.rust-lang.org/tools/install

Then in the repo run
```
cargo build --release
```
The binary will be available under `/baru/target/release`.

Of course you need the prerequisite installed in your system (see README.md)
