### ISSUE TITLE
libnetlink error: interface not found

### ISSUE THREAD

**Issue by acro5piano** [doums/baru#2]
Hi, thank you for the great tool and would love to try baru.

When I run `baru` I found the following output:

```sh
$ baru
-  -  -  -  -  -   --  -    -
libnetlink error: interface not found
```

My environment is looks like this (will provide more info if it helps):

```sh
$ uname -a
Linux archlinux 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux

$ iwctl --help
                               iwctl version 1.9
```

Do you have any suggestion to solve the issue?

Thanks

**Comment by d0m1n1q0** [comment]
Great project but very poorly written instructions. I am going to open an issue on that later.

Just to quickly help you out. I will give you an example with just two(2) modules to keep it simple.

Create a file in .config/baru/baru.yaml
Add the following for cpu and memory module

format: '%c %m'
tick: 1000
cpu:
  high_label: '!'
  format: '%v %l'
memory:
  core_inputs: 2..5
  high_label: '!'
  format: '%v %l'

Now run baru.


Every module has a letter assigned to it.
cpu is assigned to c etc etc. Check https://github.com/doums/baru/blob/master/baru.yaml

**Comment by acro5piano** [comment]
@d0m1n1q0 
Thank you for your reply. I could run baru with this minimal configuration.

```yaml
format: '%c %m'
tick: 1000
cpu:
  high_label: '!'
  format: '%v %l'
memory:
  core_inputs: 2..5
  high_label: '!'
  format: '%v %l'
```

The solution is to remove `%e` **if the pc does not have wired connection**.

```diff
-format: '%m  %c  %t  %b  %i  %s   %w%e  %a    %d'
+format: '%m  %c  %t  %b  %i  %s   %w  %a    %d'
tick: 50
battery:
  full_design: true
  low_level: 30
  full_label: '*'
  charging_label: '^'
  discharging_label: 'b'
  low_label: '!'
  unknown_label: '?'
  format: '%l %v'
brightness:
  label: 'l'
  format: '%l %v'
cpu:
  label: 'c'
  high_label: '!'
  format: '%v %l'
memory:
  core_inputs: 2..5
  label: 'm'
  high_label: '!'
  format: '%v %l'
mic:
  label: 'i'
  mute_label: '.'
  format: '%v %l'
sound:
  label: 's'
  mute_label: '.'
  format: '%v %l'
temperature:
  core_inputs: 2..5
  label: 't'
  high_label: '!'
  format: '%v %l'
wired:
  discrete: true
  label: 'e'
  disconnected_label: '\'
  format: '%l'
wireless:
  interface: wlan0
  display: Essid
  max_essid_len: 5
  label: 'w'
  disconnected_label: '\'
  format: '%v %l'
```

I still don't have any status bar (just printing on the terminal) using `spectrwm`. However, this is not relative from the original topic so I'll close this issue.

**Comment by doums** [comment]
Hi,

First please, all configuration options are detailed (exhaustively) and explained [here](https://github.com/doums/baru/blob/master/baru.yaml).

Based on the error message you get:\
for both [wireless](https://github.com/doums/baru/blob/master/baru.yaml#L612), and [wired](https://github.com/doums/baru/blob/master/baru.yaml#L554) module, there is an option to set the name of the corresponding interface.

`ip link` should give you the name of these interfaces, set it accordingly in `baru.yaml`. If this does not fix the problem please re open this issue.
