### ISSUE TITLE
Great project - instructions need improvement

### ISSUE THREAD

**Issue by d0m1n1q0** [doums/baru#3]
Congrats for the work.

The instructions to utilize the modules need a lot of work and wording. It is so poorly written that it took me half an hour to figure it out. And supposedly I know my way around.

Question now.
I invoked the modules in i3blocks and noticed that there is a string following every module. For example the memory module is followed by 'mem' (I guess by default because I removed the label instruction.
How do I go about removing the default strings?

Any plans on interactive modules?

Other than the manual, great work.
Kudos

**Comment by doums** [comment]
Hi, thank I appreciate it ! (At least for the title and the first words of the post).

Concerning your point about the "instructions" I'm not agree.\
The entire configuration is explained in https://github.com/doums/baru/blob/master/baru.yaml as noticed in the README, configuration section.
All options are exhaustively listed here, with their default value, their types and description. I understand that you have to read it and it takes a minimum of effort, but I cannot do it for you.

For your question please read https://github.com/doums/baru/blob/master/baru.yaml#L49
If you don't want the label for a module, simply omit to put `%l` in its format and you are good to go.
