### ISSUE TITLE
The configuration file example does not match the README's screenshot output.

### ISSUE THREAD

**Issue by LucDachary** [doums/baru#8]
Hi @doums!

I've bookmarked your project a while ago, since I like the output you show on your [README's screenshot](https://raw.githubusercontent.com/doums/baru/master/public/baru.png). However the configuration file you provide does not produce the same output at all:

![2021-12-29_10-09-38](https://user-images.githubusercontent.com/481435/147646032-631f8da1-e29d-47de-bc42-1d77c66dc213.png)

I sure miss some tweaks but I was hoping to have the icons and the datetime format. Would you mind uploading the `baru.yaml` you used to make the screenshot please?

Thanks for your work,
Regards

**Comment by doums** [comment]
Hi, my dotfiles are available on GitHub, so go check in it to find my config. Be sure to read `baru.yaml` to adapt it to your system.
Please note that I use a patched font for the icons. If you want icons you have to use a patched font (search for nerd font for example).
